---
title: "Teste de erro explicativo"
author: "Felipe N. S. Bezerra"
date: "20 de outubro de 2018"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
set.seed(8)
```

Gerando valores aleatórios para X1
```{r}
X1 <- rnorm(50,mean=3,sd=10)
X1
```

Gerando X2 altamente correlacionado com X1
```{r}
X2 <- 15 -0.9*X1 +rnorm(50,mean=0,sd=2)
X2
cor(X1, X2)
```

Regressão de X1 explicado por X2
```{r}
mod.X1.X2 <- lm(X1 ~ X2)
summary(mod.X1.X2)
```

Erros da regressão de X1
```{r}
e.X1.X2 <- residuals(mod.X1.X2)
e.X1.X2
cor(X1,e.X1.X2)
cor(X2, e.X1.X2)
```

Gerando Y1 como uma função de X1
```{r}
Y1 <- -9 +1.3*X1 +rnorm(50,mean=0,sd=4)
Y1
```

Modelo explicando Y1 com X1 e X2
```{r}
mod.Y1.X1X2 <- lm(Y1 ~ X1 + X2)
summary(mod.Y1.X1X2)
```

Modelo explicando Y1 com X1 e o erro do primeiro modelo
```{r}
mod.Y1.X1e1 <- lm(Y1 ~ X1 + e.X1.X2)
summary(mod.Y1.X1e1)
```


Modelo explicando Y1 com X1 e o erro do primeiro modelo
```{r}
mod.Y1.X2e1 <- lm(Y1 ~ X2 + e.X1.X2)
summary(mod.Y1.X2e1)
```






```{r}

```








